### ISSUE TITLE
Registry: Add additional comments box to confirmation page on birth and death

### ISSUE THREAD

**Issue by sarahgreisdorf** [CityOfBoston/digital#479]
Add additional comments box to confirmation page on birth and death much like marriage certificates

**Comment by reillyzlab** [comment]
Ensure this is also added to the database and the back end system so Registry can see these.

This prevents additional follow up emails and decrease potential of having to resend certificate (if they processed prior to seeing an email from constituent).

**Comment by stephaniemar** [comment]
Ask Patty

**Comment by stephaniemar** [comment]
Ideally in Birth, Death and Marriage - place to add a note. Ensure it is added to backend DB so the registry team sees the notes. This was hidden on Marriage because it was not connected to anything. 
1. Unhide Marriage comments
2. Add to Birth and Death
3. Rich needs to build connection to back end for viewing
