### ISSUE TITLE
Registry: Support multiple ID uploads

### ISSUE THREAD

**Issue by max-zjh-the** [CityOfBoston/digital#480]
On marriage certificates, I clicked on "Mine" and chose that their parents were not married and was met with this screen:
![image](https://user-images.githubusercontent.com/42783424/62574637-f64e1c80-b866-11e9-8c2a-c09e0814b4a8.png)
Then I continued with the second person and also chose that their parents were not married, but was not greeted with the previous screen's message:
![image](https://user-images.githubusercontent.com/42783424/62574691-0f56cd80-b867-11e9-8827-b3a0dd477583.png)
I was able to proceed to the ID upload page but was only prompted to upload one person's ID
![image](https://user-images.githubusercontent.com/42783424/62574433-80e24c00-b866-11e9-9bec-a2d54aee59ef.png)

**Comment by reillyzlab** [comment]
@jessicamarcus we should resolve this prior to launch.

Believe person 2 should get the potential error prompt much like person 1, correct or no?

Open question: Would they both need to upload documents? Or, would only one person need to?

**Comment by jessicamarcus** [comment]
@maxbahar it looks like the first screenshot is of the “filed in Boston?” question. The personal information questions (which include the question about parents’ marital status) come a bit later in the question flow; if the user selects “I don’t know” or ”no” for person 1, that warning will appear and the ID upload question will be added to the flow. If the user has been shown the warning for person 1, they will not see it a second time because the ID upload has already been added to the flow.

@reillyzlab we’re asking the user making the certificate request for their own ID documents, whether or not they are one of the people in the marriage.
