### ISSUE TITLE
Access Boston: Add message if user already in group

### ISSUE THREAD

**Issue by reillyzlab** [CityOfBoston/digital#548]
If a group manager tries to add a user that is already in the group there is no message alerting the group manager that the person is already in the group.

There should be a message alerting the group manager that the person is already there/has already been previously added.

**Comment by phillipbentonkelly** [comment]
Discussed design changes with Sebastian, this is what we agreed on

- On autocomplete results, add a text label that says "Already Added" to the right of the displayed text
- Selecting the "Already Added" entry in autocomplete will disable the "Add Member" button
- Change its text to "Clear" and clicking it will clear the text in the field and search results

**Comment by phillipbentonkelly** [comment]
Update: @gretchen-grozier  / @DineshBaddam this issue is not on DEV and TEST

**Comment by gretchen-grozier** [comment]
@DineshBaddam please confirm and let @phillipbentonkelly know before 4 (set for code push at 4:30)

**Comment by DineshBaddam** [comment]
Hi Phill,

I have validated this by adding Existing Person into the group again 
![image](https://user-images.githubusercontent.com/39305170/70651580-162f8b80-1c1f-11ea-8eca-dcd041d75c07.png)
![image](https://user-images.githubusercontent.com/39305170/70651647-3b23fe80-1c1f-11ea-8b1d-e8bd3ae2ab3f.png)
Now User not able to add an existing person into a group.

@phillipbentonkelly other issue is adding members into the group then deselect and select checkbox is stopping the user to add into that group.

**Here is the scenario** 

![image](https://user-images.githubusercontent.com/39305170/70652293-5d6a4c00-1c20-11ea-975c-8019ba8c2c7a.png)

Added three users into the group
![image](https://user-images.githubusercontent.com/39305170/70653092-d027f700-1c21-11ea-87e5-7015f06fbd42.png)
Deselect three users 
![image](https://user-images.githubusercontent.com/39305170/70653152-e930a800-1c21-11ea-9b2d-2ac3801af794.png)
And again select three users, here we cannot go further 
![image](https://user-images.githubusercontent.com/39305170/70653255-1bdaa080-1c22-11ea-8264-2d52234502ff.png)
Adding another user into the group, total 4 Users need to be added to that group 
![image](https://user-images.githubusercontent.com/39305170/70653331-488eb800-1c22-11ea-9c7d-8e4a2fb0d6a0.png)
Now seeing only one user has been added instead of 4 usres 
![image](https://user-images.githubusercontent.com/39305170/70653361-59d7c480-1c22-11ea-807a-363bb250572f.png)
![image](https://user-images.githubusercontent.com/39305170/70653716-0154f700-1c23-11ea-9266-c188fac96df2.png)

Finally only one user has been added 
![image](https://user-images.githubusercontent.com/39305170/70653662-e97d7300-1c22-11ea-9015-a4e61b2cf85e.png)
![image](https://user-images.githubusercontent.com/39305170/70653787-2a758780-1c23-11ea-91da-2d7b785f1413.png)


Thanks,
Dinesh.

**Comment by phillipbentonkelly** [comment]
@gretchen-grozier, @reillyzlab I am going to have to take a closer look at this. Should we go ahead pushing the other 2 issues to PROD today and coming back for this one later?

**Comment by gretchen-grozier** [comment]
@reillyzlab and @phillipbentonkelly Yes, let's do the 2 that are ready and then push this once we have it finalized

**Comment by phillipbentonkelly** [comment]
@gretchen-grozier / @DineshBaddam I pushed this change to DEV and TEST let me know if you are able to confirm.

- New UI message and functionality triggered when you try to add a user/group already in assigned
- Updating cache for the minimum groups view when an update happens (@gretchen-grozier, the issue we talked about at my desk)
- Accounting for trying to add, deselecting and then re-enabling, etc. Dinesh issue above. We updated the logic here, if you a user and then decide to not add them anymore, un-checking the checkbox removes that item from the UI. This should make it clear to the user that even though they look the same an 'added' is different than that the other items in the list.

**Comment by DineshBaddam** [comment]
@phillipbentonkelly Now Unchecking box is removing user recently added user and it is working as excepted also not able to add an existing user into the group.
Thanks,
Dinesh.

**Comment by reillyzlab** [comment]
Being deployed on 12/17.

**Comment by reillyzlab** [comment]
Confirmed deployed on 12/17.
