### ISSUE TITLE
payment-webhooks error

### ISSUE THREAD

**Issue by reillyzlab** [CityOfBoston/digital#565]
https://rollbar.com/CityofBoston/payment-webhooks-server/items/6/

*Added by Fiona*

**Comment by phillipbentonkelly** [comment]
@reillyzlab @mmcgowanBOS

Part of the error message returns the error below which leads me to believe the cause is some error on iNovah.

![COB-Stripe-Rollbar-Error-Cannot-throw-non-error-object](https://user-images.githubusercontent.com/2627273/108244880-af103f80-711d-11eb-99e5-aacfaf29c05f.JPG)

I see it last occurred on 1/28/2021 ... Is this causing any errors or problems processing payments or orders?

**Comment by reillyzlab** [comment]
It was added by Fiona and if you don't see any current issues I'm going to close and we can revisit in the future if it comes up.
