### ISSUE TITLE
Registry: Adjust language for uploading image

### ISSUE THREAD

**Issue by reillyzlab** [CityOfBoston/digital#574]
Users are having an experience issue when Internet bandwidth is low. They are giving up on the online process and calling the Registry Department thinking that the application is broken.

After looking into this we believe there are not functionality issues and that people should still be able to complete the purchase.

From what we can tell some people are having the below happen to them. The below photo shows the words 'cancel upload', but also a small, blue status bar that shows the image is uploading. These are slightly conflicting messages, so we're going to change the words 'cancel upload' to 'uploading' to try to resolve.

![IMG_3265](https://user-images.githubusercontent.com/20731897/72166321-011d5800-3397-11ea-9ad4-d1d9f1297a83.PNG)

**Comment by phillipbentonkelly** [comment]
The updated UI can now be seen on staging, https://registry-certs.digital-staging.boston.gov/birth. We changed the UI of the progress bar to be bigger and include the progress text and moved it to the top. The upload progress is only shown while a download is in progress, so only slow connections get to see it; to preview the change you'll have to downgrade the download speed in you browser prior to uploading an images. The link shows how to change the bandwidth on Google Chrome, https://www.guidingtech.com/manage-throttle-download-speed-chrome/

**Comment by reillyzlab** [comment]
@phillipbentonkelly trying to test this but keep getting this pop up, which isn't allowing me to fully get through the test.

![Screen Shot 2020-01-27 at 9 34 44 AM](https://user-images.githubusercontent.com/20731897/73183203-7358a100-40e8-11ea-80ac-f6c9850d35a0.png)

Get it all throughout the application.

**Comment by phillipbentonkelly** [comment]
Hi @reillyzlab, I haven't been able to replicate this issue on Staging. It's looks related to Google Analytics. I see from the screenshot that some analytics browser plugin is on ([Page Analytics (by Google)](https://chrome.google.com/webstore/detail/page-analytics-by-google/fnbdnhhicmebfgdgglcdacdapkcihcoh?hl=en-US)), could try turning that off and trying again, maybe the issue is related since that plugin does calls to that analytics API.

**Comment by reillyzlab** [comment]
Good call - fresh browser without that (safari) worked.

The upload screen itself looks fine. 

Potentially Related: 

1. The image acts like it's uploading (shows up) and then a few seconds later gives you the 'uploading' message (i.e. there's a large in the progress bar showing up). Flagging in case there is anything we can do.

First screen I got, then a few seconds later I got the 'uploading' bar.
![IMG_3493](https://user-images.githubusercontent.com/20731897/73214943-2513c400-4121-11ea-9880-066f1a431cde.PNG)

2. May be because I'm on staging, but getting a 'upload failed' message when image is 'done' uploading a phone. 
The upload image also has a colon that appears as if there is going to be additional text.
![IMG_3491](https://user-images.githubusercontent.com/20731897/73215122-7328c780-4121-11ea-8702-ea080c15bee7.PNG)

**Comment by phillipbentonkelly** [comment]
@reillyzlab, the two questions are related kinda.

1. The image shows up before the upload progress bar because the browser is reading it from the hard drive and not the upload process. However, the progress bar is displaying the progress of the upload to the server at the `/upload` path. When the progress hits 100% it means the server has the entire file and can go ahead and store it in the database.
2. I checked if staging is not supposed/unable to upload by swapping in the code from PROD into the staging server. It looks like only PROD can write to the DB so it's going to fail at that step. Also, the colon for the `Upload Failed` is supposed to print out and error message but we were not accounting for not having any text returned. I changed it so it only add the colon if there is a message to be appended.

I check it uploader in Safari and Firefox and I see it has two problems am working to fix. In Firefox the upload progress text is not centered and on Safari the progress bar stops before reaching 100% and it doesn't disappear even if it finished uploading the file to the server.

For the Safari issue, I think we were missing that the progress bar was stopping because before because it was barely visible. I'll be working to those things through tomorrow.

**Comment by andrebtlima** [comment]
Everything is working but spotted a few minor issues/potential ui/ux improvements after testing on prod.

We're not allowing images to be uploaded larger than 15 mb. But from a user's perspective, when you try to upload an image that is >15mb (I tried this with an image that was 15.8mb) everything seems fine when you first upload the image i.e. the progress bar starts chugging along and it gets to 99% then before telling you that the "UPLOAD FAILED."

Two potential solutions:

1. Have the error message read "UPLOAD FAILED: IMAGE TOO LARGE" or some variation of that message so that the user knows that the reason their upload failed is related to the image size. Currently you wouldn't know why the upload failed and you might just try to upload the same image again or another image that is also too large.

2. In addition to the above, have the upload reject images over 15mb immediately, so that the user doesn't have to wait for the progress bar to discover that their image was too large to begin with. This one might be a bit more complicated to do, but probably the ideal solution since it saves the user some time as well as notifying them of why their upload failed. '

Otherwise, all looks good. Tested on Chrome (both on my Mac and mobile) and Safari and things are working. Will test on Edge and comment if it has any trouble.

**Comment by phillipbentonkelly** [comment]
@andrebtlima, @reillyzlab: I was able to fix the first issue. I now show the "Image too large" label on images that were missing it. I wasn't able to address the second item (suggestion).

You can check it out at: https://registry-certs.digital-staging.boston.gov/birth?step=verifyIdentification

**Comment by reillyzlab** [comment]
As discussed in stand up, I'll take testing of this again.

**Comment by phillipbentonkelly** [comment]
The issue were the label wasn't being applied happens when the image is on the lower end of the size limit threshold. 13-14 megabytes.

**Comment by reillyzlab** [comment]
Closing this ticket because it's been resolved. 

Will open a separate ticket for other items that arose from testing.
