### ISSUE TITLE
Registry: On mobile, country names get cut off 

### ISSUE THREAD

**Issue by reillyzlab** [CityOfBoston/digital#648]
On mobile, country names get cut off. However, text should resize so that the name fits.

![IMG_5520](https://user-images.githubusercontent.com/20731897/94564668-ded1b000-022d-11eb-90da-d611b0efd4c6.jpg)

**Comment by phillipbentonkelly** [comment]
I looked into this and there seems to be no good way to style the options element in dropdowns. ```Line Break in HTML Select Option?, You can't format line breaks into an option; however, you can use the title attribute to give a mouse-over tooltip to give the full info. Use a short descriptor in the option text and give the full skinny in the title.``` I gonna move this to the done column, we can talk in our meeting if needed.

**Comment by reillyzlab** [comment]
@subaha-cob did this for neighborhood lookup. Maybe she can provide guidance.

**Comment by phillipbentonkelly** [comment]
![COB-Reg-Dropdown-font-size](https://user-images.githubusercontent.com/2627273/102788785-2ec59c00-4371-11eb-82a0-62a235069a6c.JPG)

I talked to Stella and what's she's doing there is changing the font size based on the length of the string. This doesn't look good, the screen above is what the font size would have to be in order to fit the longest country name.

**Comment by reillyzlab** [comment]
Okay, thanks for trying!

Disregard doing this and I'll close the ticket.
