### ISSUE TITLE
Registry: Issue with Data Coming Into System From App

### ISSUE THREAD

**Issue by reillyzlab** [CityOfBoston/digital#674]
There are two fields that are pushing miscellaneous data through to the back end:

1. Partnership state - this is still in a 'state' when there is no domestic partnership selected. There shouldn't be a state going in here. Or, @phillipbentonkelly can you shed some light here?

2. Place of marriage - this is only for the Registry office to fill in once the marriage license is returned so no data should be going in here.

![image](https://user-images.githubusercontent.com/20731897/96490393-5b8cf400-1206-11eb-8481-ca2b3d0b062a.png)

**Comment by phillipbentonkelly** [comment]
@reillyzlab I got questions here:

1. Is the ask to not allow Partnership State if no partnership status is selected? By default (which reflects the previous form) you the user can enter the Partnership State even if the choice of Status is blank/'Does Not Apply". What do you think we should do here? Is the ask to set the state to blank if no status has been selected aka 'Does not Apply"?

2. Replying to the email thread asking for clarification because in the DB 'boston' only comes from two columns (residence city and birth city). So it looks like this column is pulling double duty and I don't know what should happen here, cc'ing Rich for input on that too.

**Comment by mmcgowanBOS** [comment]
@reillyzlab , Phil and I met this morning for standup and in reference to his last 2 questions, Rich Oliver has addressed #2, but can you give more clarity or response on #1 ? Can you reach out to Patty too and let us know.

Thank you.

**Comment by reillyzlab** [comment]
We discussed this during 10 a.m. stand up.

The issue is that there isn't a partnerships selected and subsequently shouldn't have a place. A place can't exist if the partnership doesn't exist at all. 

Presumably the state is getting picked up from somewhere else. 

No additional information from Patty is needed.

**Comment by reillyzlab** [comment]
Passing/closing because @phillipbentonkelly says this is complete. 

Can't fully test on our end, so may re-open if Patty says this is still an issue.
